#!/usr/bin/env bash

##
# Utility code
##

TARGET=$1

CLEAR='\033[0m'
BOLD='\033[1m'
UNDERLINE='\033[4m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'

function write() {
  echo -e "$@${CLEAR}"
}

##
# Main section
##

echo
write $BOLD "\bFTL micro-benchmark\n"

# setup: clean build
write $UNDERLINE "\bCleaning"
rm -f build/*
rm -f bin/*
write $UNDERLINE "\bCompiling\n"
make $TARGET

if [ $? -eq 0 ];then
  # benchmark
  echo
  export PORT=8080
  write $UNDERLINE "\bStarting server"
  echo
  bin/ftl-$TARGET &
  sleep 0.5
  echo
  write $UNDERLINE "\bSample response"
  echo
  curl -i http://localhost:8080
  echo
  echo
  write $UNDERLINE "\bBenchmarking"
  echo
  wrk -t12 -c1000 -d20s http://localhost:8080

  # teardown
  echo
  write $UNDERLINE "\bCleaning up"
  echo
  pgrep ftl-$TARGET | xargs kill
  echo
  write $GREEN $BOLD "\b\bFinished"
  echo
fi
