#!/usr/bin/env bash

COMMAND=$1
NAME=$2
URL=$3
COMMIT=$4

DEPS="deps"

if [ "$COMMAND" == "add" ]; then
  echo "Adding git submodule: $NAME"
  git submodule add "$URL" "$DEPS/$NAME"
  cd "$DEPS/$NAME"
  git checkout "$COMMIT"
  cd ..
elif [ "$COMMAND" == "rm" ]; then
  echo "Removing git submodule: $NAME"
  git submodule deinit -f "$DEPS/$NAME"
  rm -r -f ".git/modules/$DEPS/$NAME"
  git rm -f "$DEPS/$NAME"
fi